news_sites:
  eluniversal:
    url: https://www.eluniversal.com.mx
    queries:
      XPATH_HOMEPAGE_LINKS_TO_ARTICLES: //div/*[@class="field-content" and (self::h1 or self::h2 or self::h3)]/a/@href
      XPATH_TITLE: //div[@class="pane-content"]/h1/text()
      XPATH_BODY: //div[@class="pane-content"]/div/p//text()
      XPATH_DATE: //div[@class="fechap"]/text()
      XPATH_AUTHOR: //div[contains(@class, "field-name-title")]//text()
  elpais:
    url: https://elpais.com
    queries:
      XPATH_HOMEPAGE_LINKS_TO_ARTICLES: //*[contains(concat(" ", @class, " "), " headline ")]//a/@href
      XPATH_TITLE: //div[@id="article_header"]/h1/text()
      XPATH_BODY: //div[contains(concat(" ", @class, " "), " article_body ")]/p//text()
      XPATH_DATE: //a[@class="a_ti"]/text()[1]
      XPATH_AUTHOR: //a[contains(concat(" ", @class, " "), " a_aut_n ")]/text()
  cnn: 
    url: https://cnnespanol.cnn.com/
    queries:
      XPATH_HOMEPAGE_LINKS_TO_ARTICLES: //*[@class="news__title"]/a/@href
      XPATH_TITLE: //h1[@class="storyfull__title"]/text()
      XPATH_BODY: //div[@class="storyfull__body"]/p//text()
      XPATH_DATE: //time[@class="storyfull__time"]/text()
      XPATH_AUTHOR: //p[@class="storyfull__authors"]/a[1]/text()
  pagina12:
    url: https://www.pagina12.com.ar/
    queries:
      XPATH_HOMEPAGE_LINKS_TO_ARTICLES: '//div[@class="headline-content"]//a[not(@class)]/@href'
      XPATH_TITLE: '//h1[@class="article-title"]/text()'
      XPATH_SUMMARY: '//div[@class="article-summary"]/text()'
      XPATH_BODY: '//div[@class="article-text"]/p//text()'
      XPATH_PREFIX: '//h2[@class="article-prefix"]/text()'
      XPATH_DATE: '//span[@pubdate="pubdate"]/text()'
      XPATH_AUTHOR: '//div[@class="article-main-media-header"]/div[@class="article-author"]/span/a/text()'

